import db from './db.mjs';
import fs from 'node:fs';
const out = [];
const rows = db.prepare("SELECT id, brand, model, tracked, catalog, image_url FROM smartphones WHERE model IN ('Apple Watch Series 11', 'Apple Watch Series 11 Aluminum', 'Apple Watch Series 8', 'Apple Watch Series 8 Aluminum') ORDER BY id").all();
for (const r of rows) out.push(`${r.id} | ${r.model} | t${r.tracked} c${r.catalog} | img: ${(r.image_url || 'NULL').slice(0, 90)}`);
const semimg = db.prepare("SELECT COUNT(*) c FROM smartphones WHERE tracked=1 AND (image_url IS NULL OR image_url='')").get().c;
out.push('tracked sem imagem: ' + semimg);
const comimg = db.prepare("SELECT COUNT(*) c FROM smartphones WHERE image_url IS NOT NULL AND image_url != ''").get().c;
out.push('total com imagem: ' + comimg + ' de ' + db.prepare('SELECT COUNT(*) c FROM smartphones').get().c);
fs.writeFileSync('C:/Users/roggero/AppData/Local/Temp/opencode/watches_state.txt', out.join('\n'));
console.log('done');