import fs from 'node:fs';
const out = [];
const raw = fs.readFileSync('C:/Users/roggero/Documents/New OpenCode Project/telept-camada1/data/gsm_crawled.json', 'utf8');
out.push('tamanho ficheiro: ' + raw.length);
const j = JSON.parse(raw);
out.push('tipo: ' + (Array.isArray(j) ? 'array' : typeof j));
const entries = Array.isArray(j) ? j : Object.values(j);
out.push('entradas: ' + entries.length);
if (entries[0]) out.push('primeira entrada: ' + JSON.stringify(entries[0]).slice(0, 600));
const withImg = (Array.isArray(j) ? j : Object.values(j)).filter((e) => e && (e.image || e.image_url));
out.push('com imagem: ' + withImg.length);
if (withImg[0]) out.push('exemplo img: ' + JSON.stringify(withImg[0]).slice(0, 300));
const iphone = (Array.isArray(j) ? j : Object.values(j)).filter((e) => e && String(e.name || e.model || '').includes('17 Pro Max'));
out.push('iphone 17 pro max: ' + JSON.stringify(iphone[0] || null).slice(0, 400));
fs.writeFileSync('C:/Users/roggero/AppData/Local/Temp/opencode/gsm_crawled_check.txt', out.join('\n'));
console.log('done');