import fs from 'node:fs';
import db from './db.mjs';
const out = [];
const st = fs.statSync('C:/Users/roggero/Documents/New OpenCode Project/telept-camada1/data/telept.sqlite');
out.push('data/telept.sqlite: size=' + st.size + ' mtime=' + st.mtime.toISOString());
out.push('total: ' + db.prepare('SELECT COUNT(*) c FROM smartphones').get().c);
const rows = db.prepare("SELECT id, brand, model, tracked, catalog, substr(image_url, 1, 70) img FROM smartphones WHERE model LIKE '%Series 11%' OR model LIKE '%Series 8%'").all();
for (const r of rows) out.push(`${r.id} | ${r.brand} ${r.model} | t${r.tracked} c${r.catalog} | img=${r.img || 'NULL'}`);
const up = db.prepare("SELECT COUNT(*) c FROM smartphones WHERE tracked=1 AND image_url IS NOT NULL AND image_url != ''").get().c;
out.push('tracked com imagem: ' + up);
fs.writeFileSync('C:/Users/roggero/AppData/Local/Temp/opencode/definitive.txt', out.join('\n'));
console.log('done');