import { loadIndex } from './lib/techapi.mjs';
import fs from 'node:fs';
const out = [];
const idx = loadIndex();
out.push('total index: ' + idx.length);
const e = idx.find((x) => String(x.name || '').includes('iPhone 17 Pro Max'));
out.push('iPhone 17 Pro Max entry: ' + JSON.stringify(e).slice(0, 1500));
const old = idx.find((x) => String(x.name || '').includes('Alcatel 1 2021'));
out.push('Alcatel 1 2021 entry: ' + JSON.stringify(old).slice(0, 1200));
fs.writeFileSync('C:/Users/roggero/AppData/Local/Temp/opencode/index_entry.txt', out.join('\n'));
console.log('done');